<?php

$tabid  = '403';
$tabname  = 'SupplierCorrect';

$config_tabs =  array (  	 			    
					'tabname' => 'SupplierCorrect',
					'tablabel' => 'SupplierCorrect',
					'presence' => '0',
					'customized' => '0',
					'isentitytype' => '1',
					'tabsequence' => '405',
					'ownedby' => '0',
					);

$Config_Blocks = array (
	  1 => array (	    
		'blocklabel' => 'LBL_BASE_INFORMATION',
		'sequence' => '1',
		'show_title' => '0',
		'visible' => '0',
		'create_view' => '0',
		'edit_view' => '0',
		'detail_view' => '0',
		'display_status' => '1',
		'iscustom' => '0',
		'columns' =>  '2',
	  ), 
);


$Config_Fields = array (
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'suppliers_name',
		'fieldlabel' => 'Suppliers name',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '1',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '18', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctsuppliers_name',
		'fieldlabel' => 'Correct Suppliers name',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '2',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '18', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'suppliers_shortname',
		'fieldlabel' => 'Suppliers ShortName',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '3',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctsuppliers_shortname',
		'fieldlabel' => 'Correct Suppliers ShortName',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '4',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'suppliers_username',
		'fieldlabel' => 'Suppliders Username',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '5',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctsuppliers_username',
		'fieldlabel' => 'Correct Suppliders Username',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '6',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'contact',
		'fieldlabel' => 'Contact',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '7',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '10', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctcontact',
		'fieldlabel' => 'Correct Contact',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '8',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~0',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '10', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'mobile',
		'fieldlabel' => 'Mobile',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '9',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~MO',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '10', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctmobile',
		'fieldlabel' => 'Correct Mobile',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '10',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~MO',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '10', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '208',
		'fieldname' => 'province',
		'fieldlabel' => 'Province',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '11',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O~P',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '140',
		'align' => 'center', // left,center,right
		'relation'=>'city'
	),
	array(
		'generatedtype' => '1',
		'uitype' => '208',
		'fieldname' => 'city',
		'fieldlabel' => 'City',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '12',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '1',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '140',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '208',
		'fieldname' => 'correctprovince',
		'fieldlabel' => 'Correct Province',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '13',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O~P',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '140',
		'align' => 'center', // left,center,right
		'relation'=>'correctcity'
	),
	array(
		'generatedtype' => '1',
		'uitype' => '208',
		'fieldname' => 'correctcity',
		'fieldlabel' => 'Correct City',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '14',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '1',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '140',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'company',
		'fieldlabel' => 'Company',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '1000',
		'sequence' => '15',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '80%',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctcompany',
		'fieldlabel' => 'Correct Company',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '1000',
		'sequence' => '16',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '80%',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'companyaddress',
		'fieldlabel' => 'Company Address',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '17',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '20', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctcompanyaddress',
		'fieldlabel' => 'Correct Company Address',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '18',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '20', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'bankname',
		'fieldlabel' => 'Bank name',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '19',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '20', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctbankname',
		'fieldlabel' => 'Correct Bank name',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '20',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '20', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'accountname',
		'fieldlabel' => 'Account name',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '21',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctaccountname',
		'fieldlabel' => 'Correct Account name',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '22',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'bankaccount',
		'fieldlabel' => 'Bank account',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '23',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '12', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctbankaccount',
		'fieldlabel' => 'Correct Bank account',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '24',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '12', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'ceo',
		'fieldlabel' => 'Ceo',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '25',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctceo',
		'fieldlabel' => 'Correct Ceo',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '26',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'email',
		'fieldlabel' => 'Email',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '27',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~EM',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctemail',
		'fieldlabel' => 'Correct Email',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '28',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~EM',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'editwidth' => '300',
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '305',
		'fieldname' => 'bussinesslicense',
		'fieldlabel' => 'Bussinesslicense',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '29',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'align' => 'center', // left,center,right
	),
	array(
		'generatedtype' => '1',
		'uitype' => '305',
		'fieldname' => 'correctbussinesslicense',
		'fieldlabel' => 'Correct Bussinesslicense',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '30',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'align' => 'center', // left,center,right
	), 
	array(
		'generatedtype' => '1',
		'uitype' => '305',
		'fieldname' => 'idcardfront',
		'fieldlabel' => 'Idcardfront',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '37',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'align' => 'center', // left,center,right
		'multiselect'	=> '0'
	),
	array(
		'generatedtype' => '1',
		'uitype' => '305',
		'fieldname' => 'correctidcardfront',
		'fieldlabel' => 'Correct Idcardfront',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '38',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'align' => 'center', // left,center,right
		'multiselect'	=> '0'
	),
	array(
		'generatedtype' => '1',
		'uitype' => '305',
		'fieldname' => 'idcardback',
		'fieldlabel' => 'Idcardback',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '39',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'align' => 'center', // left,center,right
		'multiselect'	=> '0'
	),
	array(
		'generatedtype' => '1',
		'uitype' => '305',
		'fieldname' => 'correctidcardback',
		'fieldlabel' => 'Correct Idcardback',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '40',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'align' => 'center', // left,center,right
		'multiselect'	=> '0'
	), 
	array(
		'generatedtype' => '1',
		'uitype' => '305',
		'fieldname' => 'logo',
		'fieldlabel' => 'Logo',
		'readonly' => '1',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '41',
		'block' => '1',
		'displaytype' => '1',
        'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'align' => 'center', // left,center,right
		'multiselect'	=> '0'
		
	),
	array(
		'generatedtype' => '1',
		'uitype' => '307',
		'fieldname' => 'correctlogo',
		'fieldlabel' => 'Correct Logo',
		'readonly' => '0',
		'presence' => '0',
		'maximumlength' => '50',
		'sequence' => '42',
		'block' => '1',
		'displaytype' => '1',
		'typeofdata' => 'F~M~250~250',
		'info_type' => 'BAS',
		'merge_column' => '0',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '8', // 4,8,12,20,30
		'align' => 'center', // left,center,right
		'multiselect'	=> '0', 
	),
 
	array (
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'longitude',
		'fieldlabel' => 'Longitude',
		'readonly' => '0',
		'presence' => '2',
		'maximumlength' => '100',
		'sequence' => '45',
		'block' => '1',
		'displaytype' => '2',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '1',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '12', // 4,8,12,20,30
		'align' => 'center', // left,center,right
	),
	array (
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'latitude',
		'fieldlabel' => 'Latitude',
		'readonly' => '0',
		'presence' => '2',
		'maximumlength' => '100',
		'sequence' => '46',
		'block' => '1',
		'displaytype' => '2',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '1',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '12', // 4,8,12,20,30
		'align' => 'center', // left,center,right
	),
	array (
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctlongitude',
		'fieldlabel' => 'Correct Longitude',
		'readonly' => '0',
		'presence' => '2',
		'maximumlength' => '100',
		'sequence' => '47',
		'block' => '1',
		'displaytype' => '2',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '1',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '12', // 4,8,12,20,30
		'align' => 'center', // left,center,right
	),
	array (
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'correctlatitude',
		'fieldlabel' => 'Correct Latitude',
		'readonly' => '0',
		'presence' => '2',
		'maximumlength' => '100',
		'sequence' => '48',
		'block' => '1',
		'displaytype' => '2',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '1',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '12', // 4,8,12,20,30
		'align' => 'center', // left,center,right
	),
	array (
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'approvalstatus',
		'fieldlabel' => 'ApprovalStatus',
		'readonly' => '0',
		'presence' => '2',
		'maximumlength' => '100',
		'sequence' => '49',
		'block' => '1',
		'displaytype' => '2',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '1',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '12', // 4,8,12,20,30
		'align' => 'center', // left,center,right
	),
	array (
		'generatedtype' => '1',
		'uitype' => '1',
		'fieldname' => 'suppliercorrectstatus',
		'fieldlabel' => 'SupplierCorrect Status',
		'readonly' => '0',
		'presence' => '2',
		'maximumlength' => '100',
		'sequence' => '50',
		'block' => '1',
		'displaytype' => '2',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '1',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '12', // 4,8,12,20,30
		'align' => 'center', // left,center,right
	),
	array (
		'generatedtype' => '1',
		'uitype' => '10',
		'fieldname' => 'supplierid',
		'fieldlabel' => 'Suppliers',
		'readonly' => '0',
		'presence' => '2',
		'maximumlength' => '100',
		'sequence' => '51',
		'block' => '1',
		'displaytype' => '2',
		'typeofdata' => 'V~O',
		'info_type' => 'BAS',
		'merge_column' => '1',
		'deputy_column' => '0',
		'show_title' => '1',
		'width' => '12', // 4,8,12,20,30
		'align' => 'center', // left,center,right
	),
);

$Config_CustomViews = array (
  array (
	'viewname' => 'Default',
	'setdefault' => '1',
	'setmetrics' => '0',
	'entitytype' => 'SupplierCorrect',
	'status' => '0',
	'cvcolumnlist' => array ('supplierid','suppliers_name','published','suppliercorrectstatus','oper'),
  ), 
);  

$Config_Ws_Entitys = array (
  1 => 
  array (
	'name' => 'SupplierCorrect',
	'handler_path' => 'include/Webservices/VtigerModuleOperation.php',
	'handler_class' => 'VtigerModuleOperation',
	'ismodule' => '1',
  ),
);

$Config_Entitynames = array (
  0 => 
  array (   
	'modulename' => 'SupplierCorrect',
	'tablename' => 'SupplierCorrect',
	'fieldname' => 'suppliers_name',
	'entityidfield' => 'xn_id',
	'entityidcolumn' => 'xn_id',
  ),
);

$config_fieldmodulerels = array (
	array (
		'fieldname' => 'supplierid',
		'module' => 'SupplierCorrect',
		'relmodule' => 'Suppliers',
		'status' => '',
		'sequence' => '0',
	)
);

$config_modentity_nums = array ( );

$config_searchcolumn = array(
	array(
		'sequence' => '1',
		'columnname' => 'published',
		'fieldname' => 'published',
		'fieldlabel' => 'Create Date',
		'type' => 'calendar',
		'info_type' => 'BAS',
		'newline' => false,
	),
  
	array(
		'sequence' => '2',
		'fieldname' => 'suppliers_nickname',
		'fieldlabel' => '供应商查询',
		'tip' => 'LBL_SEARCHTITLE',
		'type' => 'input',
		'newline' => false,
	),
    array(
        'sequence' => '3',
        'columnname' => 'suppliercorrectstatus',
        'fieldname' => 'suppliercorrectstatus',
        'fieldlabel' => 'SupplierCorrect Status',
        'type' => 'text',
        'info_type' => 'BAS',
        'newline' => false,
    ),

);


$config_picklists = array(

);

?>

