<?php 
$mod_strings = Array(
    'SupplierID'=>'商家名称',
	'LBL_BASE_INFORMATION' => '基本信息',
	'LBL_SEARCHTITLE' => '请输入商品名称或关键字',
    'Product Name'=>'商品名称',
  
    'LBL_OPER'=>'操作',
    'Mall_PropertyCorrect Status'=>'审批状态',
    'Categorys'=>'商品分类',
    'Royalty rate'=>'提成比率',
    'Barcode'=>'产品编码',
    'InternalNo'=>'内部编码',
    'Product weight'=>'商品重量',
    'Product guige' => '规格',
    'Simple Description' => '商品简单描述',
    'Description' => '描述',
    'Hit Shelf'=>'上架状态',
    'Approval Date'=>'审批时间',
    'PropertyImg'=>'属性',
    'Product Name'=>'商品名称',
    'Uploadinfo'=>'商品图片',
    'Market Price'=>'市场价',
    'Shop Price'=>'销售价',
    'QualityCertificate'=>'质检证书',
    'LBL_PROPERTY_ID' => '编号',
    'LBL_PROPERTY_DESCRIPTION' => '属性描述',
    'LBL_PROPERTY_PRICE' => '销售价格',
    'LBL_PROPERTY_MARKET' => '市场价格',
    'LBL_PROPERTY_INVENTORYS' => '初始库存',
    'LBL_PROPERTY_RECOMMEND' => '推荐',
    'LBL_PROPERTY_IMG'=>'属性图片',
    'LBL_PROPERTY_OPER'=>'操作',
    'LBL_SEARCHSUPPLIER'=>'供应商名称',
    'Data From'=>'来源',
    'SURE_DELETE_PROPERTY' => '确定要删除',
    'DELETE_PROPERTY_NO_EMPTY' => '属性类型已存有设置，是否删除？',
);
?>