<?php
global $profileid;
$recordSource = array(
	'Friends' => "friends",
    'Shares' => "shares",
    'Orders'=>'orders',
	'Complain'=>'complain',
	'ReturnedGoodsApplys'=>'returnedgoodsapplys',
    'Payments'=>'payments',
    'TakeCashs'=>'takecashs',
    'BillWaters'=>'billwaters',
	'ShareFunds'=>'sharefunds',
    'ProfileLog'=>'profilelog',
    'ActivitiesLog'=>'activitieslog',
    'Risingstarlog'=>'risingstarlog',
    'Smslog' =>'smslog',
	'Commissions' =>'commissions',
	'FrozenList' =>'frozenlist',
	'Vips' =>'vips'
);
$recordFilter = array(
	'Vips' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'Complain' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'ReturnedGoodsApplys' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'Friends' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'Shares' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	), 
	'Orders' => array(
		array('field'=>'my.purchases','logic'=>'=','value'=>$profileid),
	),
	'Payments' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'TakeCashs' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'BillWaters' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'ShareFunds' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'ActivitiesLog' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'ProfileLog' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'Risingstarlog' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'Smslog' => array(
		array('field'=>'my.mobile','logic'=>'=','value'=>$profileid),
	),
	'Commissions' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
	'FrozenList' => array(
		array('field'=>'my.profileid','logic'=>'=','value'=>$profileid),
	),
);
$fields = array( 
	'Vips' => array(
		'subordinate' =>	array('label'=>'LBL_SUBORDINATE','width'=>'8%',	'talign'=>'center',	'calign'=>'center','profileid'=>'true'), 
		'link' =>	array('label'=>'LBL_LINK',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'income' => array('label'=>'LBL_INCOME',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center'),
		'published' => array('label'=>'LBL_PUBLISHED',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center',),
	),
	'FrozenList' => array(
	    'reason'  => array('label'=>'Reason',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'execute' =>	array('label'=>'Oper User','width'=>'8%',	'talign'=>'center',	'calign'=>'center','profileid'=>'true'), 
		'handle_reason' =>	array('label'=>'Handle Reason',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'executedatetime' => array('label'=>'Execute DateTime',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center'),
		'frozenliststatus' => array('label'=>'FrozenList Status',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center',),
		'published' =>	array('label'=>'Published',		'width'=>'12%',	'talign'=>'center',	'calign'=>'center'),
	),
	'Commissions' => array(
	    'subordinate'  => array('label'=>'Subordinate User',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center','profileid'=>'true'),
		'commissionsource' =>	array('label'=>'Commission Source','width'=>'8%',	'talign'=>'center',	'calign'=>'center', 'picklist'=>'commissionsource','pickvalue'=>'picklist_valueid'), 
		'amount' =>	array('label'=>'Amount',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'money' => array('label'=>'Money',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center'),
		'orderid' => array('label'=>'Order ID',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center', 'id2no' => 'orders_no', 'idtablename' => 'orders'),
		'productid' =>	array('label'=>'Products ID',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center', 'id2no' => 'products_no', 'idtablename' => 'products'),
		'royaltyrate' =>	array('label'=>'Royalty Rate',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'commissiontype' => array('label'=>'Commission Type',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center', 'picklist'=>'commissiontype','pickvalue'=>'picklist_valueid'),
		'published' =>	array('label'=>'Published',		'width'=>'12%',	'talign'=>'center',	'calign'=>'center'),
	),
	'Complain' => array( 
		'orderid' => array('label'=>'Order ID',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center', 'id2no' => 'orders_no', 'idtablename' => 'orders'),
		'supplierid' => array('label'=>'Supplier',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center', 'id2no' => 'suppliers_name', 'idtablename' => 'suppliers'),
		'productid' => array('label'=>'Product',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center', 'id2no' => 'productname', 'idtablename' => 'products'),
		
		'consignee' =>	array('label'=>'Consignee',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'), 
		'mobile' =>	array('label'=>'Mobile',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'submitdatetime' =>	array('label'=>'Submit DateTime',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'complainresult' =>	array('label'=>'Complain Reason',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'complainstatus' =>	array('label'=>'Complain Status',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'execute' =>	array('label'=>'Oper User',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center','profileid'=>'true'),
		'trackno' =>	array('label'=>'Track No',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'lastdatetime'  =>	array('label'=>'Last DateTime',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'published' => array('label'=>'Published',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'),
	),
	'ReturnedGoodsApplys' => array( 
		'orderid' => array('label'=>'Order ID',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center', 'id2no' => 'orders_no', 'idtablename' => 'orders'),
		'supplierid' => array('label'=>'Supplier',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center', 'id2no' => 'suppliers_name', 'idtablename' => 'suppliers'),
		'productid' => array('label'=>'Product',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center', 'id2no' => 'productname', 'idtablename' => 'products'),
		'consignee'  =>	array('label'=>'Consignee',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'mobile'  =>	array('label'=>'Mobile',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'trackno' =>	array('label'=>'Track No',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'execute' =>	array('label'=>'Oper User',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center','profileid'=>'true'),
		'lastdatetime'  =>	array('label'=>'Last DateTime',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'responsibility' =>	array('label'=>'Responsibility',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'returnedgoodsapplysstatus'  =>	array('label'=>'ReturnedGoodsApplys Status',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'published' => array('label'=>'Published',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'),
	), 
	'Friends' => array( 
		'friendid' =>	array('label'=>'Friend Profile', 'width'=>'8%',	'talign'=>'center',	'calign'=>'center','profileid'=>'true'),
		'origin' =>	array('label'=>'Origin',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'), 
		'published' => array('label'=>'Published',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'),
	),
	'Shares' => array( 
		'sharepage' =>	array('label'=>'Share Page',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center', 'picklist'=>'sharepage','pickvalue'=>'picklist_valueid'),
		'sharedate' =>	array('label'=>'Share Date',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'sharefund' => array('label'=>'Share Fund',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'),
		'amount' => array('label'=>'Amount',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'), 
		'uv' =>	array('label'=>'Uv',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'orderscount' => array('label'=>'Orders Count',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'),
		'ip' => array('label'=>'Share Ip',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'),
		'system' => array('label'=>'Mobile System',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'),
		'browser' => array('label'=>'Browser',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'),
		'published' => array('label'=>'Share DateTime',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'),
	),
	'Orders' => array(
		'orders_no' =>	array('label'=>'Orders No',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'ordername' =>	array('label'=>'Order name',	'width'=>'15%',	'talign'=>'center',	'calign'=>'center'),
		'consignee' =>	array('label'=>'Consignee',	'width'=>'5%',	'talign'=>'center',	'calign'=>'center'),
		'mobile' => array('label'=>'Mobile',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center'),
		'address' =>	array('label'=>'Address',		'width'=>'17%',	'talign'=>'center',	'calign'=>'center'),
        'payment'=>array('label'=>'Payment',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'sumorderstotal' =>	array('label'=>'Sum orders total',	'width'=>'5%',	'talign'=>'center',	'calign'=>'center'),
		'order_status' =>	array('label'=>'Orders Status',	'width'=>'5%',	'talign'=>'center',	'calign'=>'center'),
		'singletime' => array('label'=>'Single time',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center'),
		'paymenttime' => array('label'=>'Payment time',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center'),
        'confirmreceipt_time' => array('label'=>'确定收货',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center'),
	),
	'Payments' => array(
		'payments_no' =>	array('label'=>'Payments No',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'buyer_email' =>	array('label'=>'Buyer_Email',	'width'=>'15%',	'talign'=>'center',	'calign'=>'center'),
		'payment' =>	array('label'=>'Payment',	'width'=>'5%',	'talign'=>'center',	'calign'=>'center'),
		'orderid' => array('label'=>'Order ID',	'width'=>'10%',	'talign'=>'left',	'calign'=>'center', 'id2no' => 'orders_no', 'idtablename' => 'orders'),
		'subject' =>	array('label'=>'Subject',		'width'=>'25%',	'talign'=>'center',	'calign'=>'center'),
		'trade_no' =>	array('label'=>'Trade no',	'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'amount' => array('label'=>'Amount',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center'),
		'total_fee' =>	array('label'=>'Total_Fee',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'paymentdatetime' =>	array('label'=>'Payment DateTime',	'width'=>'15%',	'talign'=>'center',	'calign'=>'center'),
	),
	'TakeCashs' => array(
		'bank' =>	array('label'=>'Bank',		'width'=>'15%',	'talign'=>'center',	'calign'=>'center'),
		'bankname' =>	array('label'=>'BankName',	'width'=>'6%',	'talign'=>'center',	'calign'=>'center'),
		'bankaccount' =>	array('label'=>'Bank Account',	'width'=>'15%',	'talign'=>'center',	'calign'=>'center'),
		'money' => array('label'=>'Money',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center'),
		'amount' =>	array('label'=>'Amount',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'newmoney' =>	array('label'=>'New Money',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'takecashsdatetime' => array('label'=>'TakeCashs DateTime',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center'),
		'takecashsstatus' =>	array('label'=>'Takecashs Status',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
	),
	'BillWaters' => array(
	    'id' =>	array('label'=>'BillWaters No',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'billwatertype' =>	array('label'=>'Bill Water Type','width'=>'8%',	'talign'=>'center',	'calign'=>'center', 'picklist'=>'billwatertype','pickvalue'=>'picklist_valueid'),
		'sharedate' =>	array('label'=>'Share Date',	'width'=>'6%',	'talign'=>'center',	'calign'=>'center'),
		'amount' =>	array('label'=>'Amount',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'money' => array('label'=>'Money',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center'),
		'shareid' =>	array('label'=>'Share ID',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'takecashid' =>	array('label'=>'TakeCashs ID',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'orderid' => array('label'=>'Order ID',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center', 'id2no' => 'orders_no', 'idtablename' => 'orders'),
		'productid' =>	array('label'=>'Products ID',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center', 'id2no' => 'products_no', 'idtablename' => 'products'),
		'royaltyrate' =>	array('label'=>'Royalty Rate',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'commissiontype' => array('label'=>'Commission Type',	'width'=>'8%',	'talign'=>'left',	'calign'=>'center', 'picklist'=>'commissiontype','pickvalue'=>'picklist_valueid'),
		'inviteprofileid' =>	array('label'=>'Invite Profile',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center','profileid'=>'true'),
		'middleman' =>	array('label'=>'Middle Invite Profile',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center','profileid'=>'true'),
		'published' =>	array('label'=>'Submit DateTime',		'width'=>'12%',	'talign'=>'center',	'calign'=>'center'),
	),
	'ShareFunds' => array(
		'id' => array('label'=>'Shares No',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'sharefundtype' => array('label'=>'Share Fund Type',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center',	'picklist'=>'sharefundtype','pickvalue'=>'picklist_valueid'),
		'amount' => array('label'=>'Amount',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'sharefund' => array('label'=>'Share Fund',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'money' => array('label'=>'Money',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'shareid' => array('label'=>'Share ID',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'orderid' => array('label'=>'Order ID',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center',	'id2no' => 'orders_no', 'idtablename' => 'orders'),
		'fundrate' => array('label'=>'Fund Rate',	'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'published'=> array('label'=>'published',	'width'=>'12%',	'talign'=>'center',	'calign'=>'center'),
	),
	'ProfileLog' => array(
		'id' => array('label'=>'ProfileLog No',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'operprofileid' => array('label'=>'Oper User',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center',	'profileid'=>'true'),
		'opertype' => array('label'=>'Oper Type',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'oldrank' => array('label'=>'Old Rank',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'rank' => array('label'=>'Rank',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'oldmoney' => array('label'=>'Old Money',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'amount' => array('label'=>'Amount',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'money' => array('label'=>'Money',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'published' => array('label'=>'published',		'width'=>'12%',	'talign'=>'center',	'calign'=>'center'),
	),
	'ActivitiesLog' => array(
		'id' => array('label'=>'ActivitiesLog No',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'activitieid' => array('label'=>'Activitie ID',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center', 'id2no' => 'activities_no', 'idtablename' => 'activities'),
		'oldrank' => array('label'=>'Old Rank',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'addrank' => array('label'=>'Add Rank',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'rank' => array('label'=>'Rank',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'oldmoney' => array('label'=>'Old Money',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'amount' => array('label'=>'Amount',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'money' => array('label'=>'Money',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'published' => array('label'=>'published',		'width'=>'12%',	'talign'=>'center',	'calign'=>'center'),
        'oldsharefund'=> array('label'=>'历史分享基金',		'width'=>'12%',	'talign'=>'center',	'calign'=>'center'),
        'addsharefund'=> array('label'=>'增加分享基金',		'width'=>'12%',	'talign'=>'center',	'calign'=>'center'),
        'sharefund'=> array('label'=>'新分享基金',		'width'=>'12%',	'talign'=>'center',	'calign'=>'center'),
	),
	'Risingstarlog' => array(
		'id' => array('label'=>'Risingstarlog No',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'level' => array('label'=>'User level',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'rank' => array('label'=>'Rank',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'trigger' => array('label'=>'Trigger Source',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'startype' => array('label'=>'Star type',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center', 'picklist'=>'startype','pickvalue'=>'picklist_valueid'),
	    'published' => array('label'=>'published',		'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
	),
	'Smslog' => array(
		'id' => array('label'=>'Smslog No',		'width'=>'8%',	'talign'=>'center',	'calign'=>'center'),
		'smslogid' => array('label'=>'Smslog ID',		'width'=>'16%',	'talign'=>'center',	'calign'=>'center'),
		'sendtype' => array('label'=>'Send Type',		'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'published' => array('label'=>'published',		'width'=>'10%',	'talign'=>'center',	'calign'=>'center'),
		'smsinfo' => array('label'=>'SMS Info',		'width'=>'30%',	'talign'=>'center',	'calign'=>'center'),
	),
);

?>