<?php 
$mod_strings = Array(
    'LBL_BASE_INFORMATION' => '基本信息',
    'SupplierID'=>'商家名称',
    'Oper User'=>'操作人',
    'Mall Name'=>'商城名称',
    'Official website'=>'官方网站',
    'Categorys Level'=>'分类级别',  
	'Index Columns'=>'首页商品展示分栏',
	'Categorys Columns' =>'分类商品展示分栏',
	'Theme Color'=>'标题基色',
	'Text Color' =>'文本颜色',
	'Button Color' =>'按钮颜色',
	'Product Price Color' =>'商品价格颜色',
	'Product background Color' =>'商品背景基色',
	'b2bsetting' =>'B2B专用设置',
	'Show Vendor' => '供应商信息',
	'Total Price Free Shipping' => '总价包邮',
	'Total Quantity Free Shipping' => '总件数包邮',
	
    'MainPage Show Object' => '首页展示对象',
	'Force Activation' => '强制激活',
	'Sourcer Required' => '推荐人必填',
	'Allow Share' => '分享',
	'Show UniqueSale' => '资格商品展示',
	
	'Allow Qrcode' => '推广二维码', 
	'Popularize Qrcode' => '推广二维码发放模式',
	'Allow PhysicalStore' => '实体店',
	'Default PhysicalStore Rate' => '默认实体店分佣比率',
	'Product Qrcode' => '展示产品二维码',
	'Product Display Mode' => '图文详情展示方式',
	'Reception' => '商品签到分次消费',
	'My Logistic' => '自有物流',
	'My Logistic Name' => '自有物流名称',
	'Real Name Authentication'  => '实名认证',
	'Authentication Payment'  => '认证支付',
	'Pre Sales Consultation'  => '售前咨询',
	'Product Appraises'  => '商品评价',
	'Auto Deliver Rechargeable Card' => '充值卡自动发货',
	'Commission Mode' => '分销佣金发放方式',
	'Allow Returngoods' => '允许退货',
	'MainPage Slider' => '首页轮播图',
	'Bottom Ad Logo' => '底部广告图',
	'Top Ad Logo' => '顶部广告图',
	'MainPage Product Show Mode'=> '首页商品展示模式', 
	'MainPage Title' => '首页标题',
	'Show Category' => '导航栏分类显示',
	'Show Promotion Center' => '导航栏推广中心显示',
	'Show FuBiSi' => '福布斯',
	'Show Trade Order Record' => '详情页成交记录',
);
?>